package:                                                                                   
    name: naivestates                                                            
    version: 1.6.1 

requirements:                                                                     
    build:                                                                       
        - r-base=3.6
        - r-devtools                                                          
    run:                                                                         
        - r-base=3.6                                                      
        - r-tidyverse=1.3.0                                                      
        - r-mixtools=1.2.0                                                       
        - r-egg=0.4.5                                                            
        - r-devtools=2.3.0                                                       
        - r-optparse=1.6.6                                                       
        - r-ggthemes=4.2.0                                                       
        - r-uwot=0.1.8                                                           
about:                                                                           
    home: https://github.com/labsyspharm/naivestates                             
    license: MIT License                                                         
    summary: "naivestates is a label-free, cluster-free tool for inferring cell types from quantified marker expression data"
